### ISSUE TITLE
Şifrelenmeden giden paketler hakkında

### ISSUE THREAD

**Issue by V3YNjKbFGLSQ0FzpOu1s** [mucahidkambur/tdk-sozluk#2]
![2021-03-13_01-05](https://user-images.githubusercontent.com/69808482/111003647-7449a200-837f-11eb-85a1-ec52a015f488.png)
Merhaba hocam,
Süper uygulama, lakin TDK ile kurulan bazı bağlantıların şifrelenmediğini görüyorum. Uygulamanın daha güvenli olması adına böyle bir özellik eklenebilir mi diye merak etmekteyim. Eğer mümkünse bu issue naçizane bir feature request olarak da düşünülebilir.
Teşekkürler.

**Comment by mucahidkambur** [comment]
Selamlar, yorumun için teşekkürler. Uygulama tamamen GET isteklerinden oluştuğu için güvenlik konusu çok da önemli değil. SSL pinning tarzına bir şeyler yapılabilir ama overengineering olur diye düşünüyorum. Eğer kaçırdığım bir güvenlik açığı varsa paylaşabilirsin.
